### ISSUE TITLE
TurnToHeadUseCameraSetting does not do anything?

### ISSUE THREAD

**Issue by cafeplays** [isieo/VMCBlendshapeInterceptor#5]
i tried turning it off and turn it on.. i don't see a difference.
also turn to head does not keep track of my head after the camera stops moving

**Comment by isieo** [comment]
I forgot to remove TurnToHeadUseCameraSetting from the documentation, please ignore it.
TurnToHead only works when the camera is "animating", when the camera is in the "delay" part of the script, it will not do the calculations, a workaround is to make a dummy motion section with the same start position and end position and set the duration of the section to how long you want the camera to look at you. 

If you wish to change anything feel free to send a pull request, i'll review the code and merge it
